# Generated by Django 6.0.3 on 2026-04-06 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='포스터 제목', max_length=200)),
                ('description', models.TextField(blank=True, help_text='포스터에 대한 설명이나 캠페인 문구')),
                ('image', models.ImageField(help_text='캠페인 포스터 이미지', upload_to='posters/')),
                ('is_active', models.BooleanField(default=True, help_text='현재 슬라이드쇼에 표시할지 여부')),
                ('order', models.IntegerField(default=0, help_text='표시 순서 (낮을수록 먼저 표시)')),
            ],
            options={
                'verbose_name': '포스터',
                'verbose_name_plural': '포스터 목록',
                'ordering': ['order', '-id'],
            },
        ),
    ]
