# Generated by Django 6.0.3 on 2026-04-06 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlobalSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slideshow_interval', models.IntegerField(default=5, help_text='슬라이드 전환 간격 (초 단위)')),
            ],
            options={
                'verbose_name': '설정',
                'verbose_name_plural': '설정',
            },
        ),
    ]
