# Generated by Django 6.0.3 on 2026-04-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_globalsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='poster',
            name='custom_duration',
            field=models.IntegerField(blank=True, help_text='이 개별 포스터만의 표시 시간 (초 단위). 비워두면 기본 설정을 따릅니다.', null=True),
        ),
    ]
