"""Code generation orchestrator: YAML config → complete Zephyr project."""
from __future__ import annotations

from pathlib import Path

from .schema import ZephyrHomeConfig
from .components.base import GeneratorContext
from .components.network import contribute_network
from .components.sensor.bme280 import BME280Generator
from .components.sensor.generic import GenericSensorGenerator
from .components.switch.gpio import GPIOSwitchGenerator

_SENSOR_GENERATORS = {
    "bme280": BME280Generator,
}
_SWITCH_GENERATORS = {
    "gpio": GPIOSwitchGenerator,
}


def generate_project(cfg: ZephyrHomeConfig, output_dir: Path) -> None:
    """Create a complete, west-buildable Zephyr project from cfg."""
    output_dir.mkdir(parents=True, exist_ok=True)
    (output_dir / "src").mkdir(exist_ok=True)
    (output_dir / "boards").mkdir(exist_ok=True)

    ctx = GeneratorContext(output_dir=output_dir, device_name=cfg.device.name)

    # 1. Network / OpenThread Kconfig
    contribute_network(cfg.network, ctx)

    # 2. Sensor components
    for sensor in cfg.sensors:
        driver = getattr(sensor, "driver", None)
        platform = sensor.platform
        key = driver or platform
        GenClass = _SENSOR_GENERATORS.get(key, GenericSensorGenerator)
        GenClass(sensor).contribute(ctx)

    # 3. Switch components
    for switch in cfg.switches:
        GenClass = _SWITCH_GENERATORS.get(switch.platform)
        if GenClass is None:
            raise ValueError(f"Unsupported switch platform: {switch.platform!r}")
        GenClass(switch).contribute(ctx)

    # 4. Write all output files
    _write_prj_conf(cfg, ctx)
    _write_overlay(cfg, ctx)
    _write_cmake(cfg, ctx)
    _write_generated_c(ctx)
    _write_main_c(output_dir)


# ── File emitters ────────────────────────────────────────────────────────────

def _write_prj_conf(cfg: ZephyrHomeConfig, ctx: GeneratorContext) -> None:
    lines = [
        "# Auto-generated by ZephyrHome CLI — do not edit",
        f"# Device: {cfg.device.name}",
        "",
        "# ── ZephyrHome core ──",
        "CONFIG_ZEPHYRHOME=y",
        f'CONFIG_ZEPHYRHOME_DEVICE_NAME="{cfg.device.name}"',
        f'CONFIG_ZEPHYRHOME_FRIENDLY_NAME="{cfg.device.friendly_name or cfg.device.name}"',
        "CONFIG_ZEPHYRHOME_ANNOUNCE_INTERVAL_SEC=30",
        "",
        "# ── Network + component config ──",
        *ctx.kconfig_lines,
    ]
    (ctx.output_dir / "prj.conf").write_text("\n".join(lines) + "\n")


def _write_overlay(cfg: ZephyrHomeConfig, ctx: GeneratorContext) -> None:
    parts = ["/* Auto-generated by ZephyrHome CLI — do not edit */", ""]
    parts.extend(ctx.overlay_nodes)
    (ctx.output_dir / "app.overlay").write_text("\n".join(parts) + "\n")


def _write_cmake(cfg: ZephyrHomeConfig, ctx: GeneratorContext) -> None:
    comp_add = "\n".join(
        f"add_subdirectory(${{ZEPHYRHOME_BASE}}/firmware/components/{d} zh_{d})"
        for d in ctx.cmake_component_dirs
    )
    content = (
        "# Auto-generated by ZephyrHome CLI — do not edit\n"
        "cmake_minimum_required(VERSION 3.20.0)\n\n"
        "# Export ZEPHYRHOME_BASE before running west build:\n"
        "#   export ZEPHYRHOME_BASE=/path/to/school-campaign/zephyrhome\n"
        "if(NOT DEFINED ENV{ZEPHYRHOME_BASE})\n"
        "    message(FATAL_ERROR \"Set ZEPHYRHOME_BASE to the zephyrhome/ directory root\")\n"
        "endif()\n"
        "set(ZEPHYRHOME_BASE $ENV{ZEPHYRHOME_BASE})\n\n"
        "find_package(Zephyr REQUIRED HINTS $ENV{ZEPHYR_BASE})\n"
        f"project({cfg.device.name})\n\n"
        "add_subdirectory(${ZEPHYRHOME_BASE}/firmware/base zh_base)\n"
        f"{comp_add}\n\n"
        "target_sources(app PRIVATE\n"
        "    src/main.c\n"
        "    src/zh_generated.c\n"
        ")\n\n"
        "target_include_directories(app PRIVATE\n"
        "    ${ZEPHYRHOME_BASE}/firmware/base/include\n"
        "    src\n"
        ")\n"
    )
    (ctx.output_dir / "CMakeLists.txt").write_text(content)


def _write_generated_c(ctx: GeneratorContext) -> None:
    includes = "\n".join(ctx.c_includes) or ""
    init_body = "\n    ".join(ctx.c_init_calls) if ctx.c_init_calls else "/* no components */"
    content = (
        "/* Auto-generated by ZephyrHome CLI — do not edit */\n"
        '#include "zh_component.h"\n'
        f"{includes}\n\n"
        "void zh_components_init(void)\n"
        "{\n"
        f"    {init_body}\n"
        "}\n"
    )
    (ctx.output_dir / "src" / "zh_generated.c").write_text(content)


def _write_main_c(output_dir: Path) -> None:
    content = (
        "/* Auto-generated by ZephyrHome CLI — do not edit */\n"
        "#include <zephyr/kernel.h>\n"
        '#include "zh_main.h"\n\n'
        "int main(void)\n"
        "{\n"
        "    return zh_main_run();\n"
        "}\n"
    )
    (output_dir / "src" / "main.c").write_text(content)
